image: python:alpine

stages:
- test
- deploy

variables:
  # The following variables are setup via gitlab project group:
  # SSH_PRIVATE_KEY
  MAKEFILE: "make -C .travis/"

build_only:
  stage: test
  script:
    - apk add --no-cache make git
    - $MAKEFILE execute-CI

build_and_publish:
  stage: deploy
  # only:
  #   - master
  before_script:
    - apk add --no-cache make git
  script:
    - $MAKEFILE execute-CI
    - $MAKEFILE push
