language: python
python:
  - 3.5

git:
  depth: 10


env:
#   global:
#   - secure: "PASTE ENCRYPTED RESULT HERE"
  - MAKEFILE: make -C ./travis

script: 
- $MAKEFILE execute-CI

after_success:
  only:
  - master
  script:
  - $MAKEFILE push
