dist: xenial
language: python
python: 3.6

env:
  global:
  - PATH="$PATH:/$(whoami)/.local/bin"

# before_install:
#   - sudo apt-get install make git pip


script:
  - make -C .travis execute-CI
  - make html


deploy:
  provider: pages
  local-dir: _build/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
